name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache MPI installation
        id: cache-mpi
        uses: actions/cache@v1
        with:
          path: ~/mpich
          key: ${{ runner.os }}-mpi
      - name: Install MPI
        if: steps.cache-mpi.outputs.cache-hit != 'true'
        run: sh ./conf/travis-install-mpi.sh mpich
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest numpy jax jaxlib mpi4py
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -v .
      - name: Single-execution test with pytest
        run: |
          cd tests 
          pytest .
      - name: mpirun test with pytest
        run: |
          mpirun -np 2 pytest .
